project_id = "ltgampdtawuefwwayncx"


[functions.chat-alibaba]
verify_jwt = false

[functions.chat-slides-stream]
verify_jwt = false

[functions.slides-api]
verify_jwt = false

[functions.slides-export-pptx]
verify_jwt = false

[functions.deep-research-job]
verify_jwt = false

[functions.docs-generate]
verify_jwt = false

[functions.telegram-tasks-bot]
verify_jwt = false

[functions.kimi-coder]
verify_jwt = false

[functions.kashier-webhook]
verify_jwt = false



[functions.send-scheduled-messages]
verify_jwt = false

[functions.crawl-url]
verify_jwt = false

[functions.create-scheduled-message]
verify_jwt = false

[functions.parallel-webhook]
verify_jwt = false

[functions.parallel-run]
verify_jwt = false

[functions.pipedream-connect]
verify_jwt = false

[functions.oauth-github-connect]
verify_jwt = false

[functions.oauth-supabase-connect]
verify_jwt = false

[functions.supabase-oauth-start]
verify_jwt = false

[functions.github-push]
verify_jwt = false

[functions.supabase-link-manager]
verify_jwt = false

[functions.telegram-keys-bot]
verify_jwt = false

[functions.appsumo-webhook]
verify_jwt = false

[functions.appsumo-oauth]
verify_jwt = false

